[package]
name = "dash-vm"
version = "0.1.0"
authors = ["jarontai <jaroncn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
