import 'package:dart_style/dart_style.dart';

final Map<String, Map<String, String>> astMap = {
  'Expression': {
    'AssignExpression': 'Token name, Expression value',
    'BinaryExpression': 'Expression left, Token op, Expression right',
    'CallExpression': 'Expression callee, Token paren, List<Expression> arguments',
    'GetExpression': 'Expression object, Token name',
    'SetExpression': 'Expression object, Token name, Expression value',
    'ThisExpression': 'Token keyword',
    'GroupingExpression': 'Expression expression',
    'LiteralExpression': 'Object value',
    'LogicalExpression': 'Expression left, Token op, Expression right',
    'UnaryExpression': 'Token op, Expression right',
    'VariableExpression': 'Token name',
  },
  'Statement': {
    'BlockStatement': 'List<Statement> statements',
    'ClassStatement': 'Token name, List<FunctionStatement> methods',
    'ExpressionStatement': 'Expression expression',
    'IfStatement': 'Expression condition, Statement thenBranch, Statement elseBranch',
    'FunctionStatement': 'Token name, List<Token> params, List<Statement> body',
    'ReturnStatement': 'Token keyword, Expression value',
    'VarStatement': 'Token name, Expression initializer',
    'WhileStatement': 'Expression condition, Statement body',
  },  
};

String run() {
  var sb = StringBuffer();

  sb.writeln(
      '// These code was generated by ast_gen, please don\'t modify directly.');

  sb.writeln();

  sb.writeln("import '../scanner/token.dart';");

  sb.writeln();

  sb.writeln('// The ast expressions and statements.');

  sb.writeln();

  for (var baseName in astMap.keys) {
    sb.writeln('abstract class $baseName {');

    sb.writeln('R accept${baseName}<R>(${baseName}Visitor<R> visitor);');

    sb.writeln('}');

    for (var entry in astMap[baseName].entries) {
      var className = entry.key;
      var fields = entry.value;

      sb.writeln();
      sb.writeln('class $className extends $baseName {');

      fields.split(',').forEach((field) {
        sb.writeln('final $field;');
      });

      var args = fields.split(',').map((field) {
        return 'this.${field.trim().split(' ')[1]}';
      }).join(',');
      sb.writeln('$className($args);');

      sb.writeln();

      sb.writeln('R accept${baseName}<R>(${baseName}Visitor<R> visitor) {');
      sb.writeln('return visitor.visit$className(this);');
      sb.writeln('}');

      sb.writeln('}');

      sb.writeln();
    }

    sb.writeln('abstract class ${baseName}Visitor<R> {');
    astMap[baseName].keys.forEach((className) {
      sb.writeln('R visit$className($className ${baseName.toLowerCase()});');
    });
    sb.writeln('}');

    sb.writeln();
    sb.writeln();
    sb.writeln();
  }

  return DartFormatter().format(sb.toString());
}
